name: doker-kompos

services:
  frontend:
    build: ./frontend
    ports:
      - 4444:80
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - 3001:3001
    networks:
      - my-network
    depends_on:
      - monggodebe
      - cache
    # environment:
    #   - MONGO_URL=mongodb://kiwkiw:27017/mydb
    env_file:
      - ./backend/.env

  monggodebe:
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - mongo_data:/data/db

  cache:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - redis_data:/data

networks:
  my-network:

volumes:
  mongo_data:
  redis_data:
