name: doker-kompos

services:
  frontend:
    # image: skyespirates/compose-frontend
    build: ./frontend
    ports:
      - 4444:80
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    # image: skyespirates/compose-backend
    build: ./backend
    ports:
      - 3001:3001
    networks:
      - my-network
    depends_on:
      - monggodebe
      - cache
    # environment:
    #   - MONGO_URL=mongodb://kiwkiw:27017/mydb
    env_file:
      - ./backend/.env

  some-service:
    # image: skyespirates/compose-some-service
    build: ./some-service
    ports:
      - 3002:3002
    networks:
      - my-network
    depends_on:
      maisekuel:
        condition: service_healthy # make sure mysql container is ready before running this service
      cache:
        condition: service_started
    env_file:
      - ./some-service/.env

  kong-service:
    image: kong/kong-gateway:latest
    restart: unless-stopped
    ports:
      - "7000:8000" # Proxy
      - "7443:8443" # Proxy (SSL)
      - "8001:8001" # Admin
      - "7002:8002" # GUI
      - "7444:8444" # Admin (SSL)
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://localhost:7002
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
    volumes:
      - ./kong-service/kong.yml:/kong/declarative/kong.yml
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  monggodebe:
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - mongo_data:/data/db

  maisekuel:
    image: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck: # healthcheck mechanism
      test:
        ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -u root -psecret"]
      interval: 10s
      retries: 5

  cache:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - redis_data:/data

networks:
  my-network:

volumes:
  mongo_data:
  redis_data:
  mysql_data:
